### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Hurd8x** [Mcdouglas-X/BigDb#1]
keyhunt cant work with 1,000,000 point, all regivme's I was try.

I make this :

priv in outlut is a priv of substracted pubkey

[code]
import hashlib
import ecdsa
N =  (2**256 - 2**32 - 2**9 - 2**8 - 2**7 - 2**6 - 2**4 - 1)#  115792089237316195423570985008687907852837564279074904382605163141518161494337

def inv(v): return pow(v, N-2, N)
def divnum(a, b): return ( (a * inv(b) ) % N )

G_x = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
G_y = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8

P_x=0xfe01eba87de8b92e872b3bb7bcb161b9611a70012e96cecca87590bed92c15b1  #(k * G_x) % (2**256 - 2**32 - 2**9 - 2**8 - 2**7 - 2**6 - 2**4 - 1)
P_y = 0xdbc6315173afdf48da195367b827fe2cf1b6047798f152c9306bb2db9435a119

P_inv = (inv(G_x))

P_inv = ((P_inv * 2%N) %N + P_inv % N) %N

sec = 0x34228895d231df0f17001f5 

0x578540107395a50d1725e1be25d183fad

priv = 0

i =1#2**49# 0x47eb1a9a2c802d111ddef980016130e35 - 0xe359
k = 0

K = 0
while i <= 2**90 and sec - i >= 2**88:
    
    #0x1cc6cfbfe0217e5ba5ff2eb816130e35
    K = K +1
    
    
    priv = P_x % ((P_inv* i%N)%N)
    if priv == P_x:
        k = k +1
        print("priv",(hex((0x34228895d231df0f17001f5- i))))
        #print("div",(divnum( 0x2d7ab6a05aa37 - (0x2d7ab6a05aa37- i), 50000000)))
        #print(hex(i))
        
        
        
        #print(hex( 0x2d7ab6a05aa37 - (0x2d7ab6a05aa37- i)))
        
        #print(hex( 0x2d7ab6a05aa37))
        print("iIii",hex(i),i,"K",K,"k",k)
    
    i = i+10000000000000000000 -1

[/code]

result:

3991
priv 0x100011a8f5b4002da0001f4
iIii 0x242276ecdc7ddee17700001 698945340000000000000000001 K 69894535 k 543992
priv 0x10000bef1e52203cfd801f4
iIii 0x24227ca6b3dfbed21980001 698947030000000000000000001 K 69894704 k 543993
priv 0x1000076d86ff0a82a5001f4
iIii 0x242281284b32d48c7200001 698948360000000000000000001 K 69894837 k 543994
priv 0x100001b3af9d2a9202801f4
iIii 0x242286e22294b47d1480001 698950050000000000000000001 K 69895006 k 543995

K this is total pubkeys

k this is mach smaler pubkeys what is good  for brute

Can you implement k to your scrypt

with sach param:

[code]
while i <= 2**90 and sec - i >= 0x1b3af9d2a9202801f4 and sec - i >=0:#2**8:

[/code]

result:

784884
priv 0xc3d06aa7760afac0af
iIii 0x34227c58cb8767ae6754146 1008431949999999999899156806 K 100843196 k 784885
priv 0x8bfa4b90a28ea2c116
iIii 0x34227fd62d78d4e62cd40df 1008432979999999999899156703 K 100843299 k 784886
priv 0x54242c79cf124ac17d
iIii 0x342283538f6a421df254078 1008434009999999999899156600 K 100843402 k 784887
priv 0x1c4e0d62fb95f2c1e4
iIii 0x342286d0f15baf55b7d4011 1008435039999999999899156497 K 100843505 k 784888

so, 0x1c4e0d62fb95f2c1e4 - one pubkey 2^69 in 784888 pubkeys

input key 2^90  0x34228895d231df0f17001f5

What you think ???

**Comment by Mcdouglas-X** [comment]
Hello, this is not a problem.
